AppAFCEPFWeb/src/main/java/fr/pocolobo/afcepf/controller/pedago/EditionCursusBean.java
package fr.pocolobo.afcepf.controller.pedago;

import java.io.Serializable;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;

import fr.pocolobo.afcepf.business.api.CursusIBusiness;
import fr.pocolobo.afcepf.business.api.ModuleIBusiness;
import fr.pocolobo.afcepf.controller.AccessManager;
import fr.pocolobo.afcepf.controller.ConnexionBean;
import fr.pocolobo.afcepf.controller.NavigationBean;
import fr.pocolobo.afcepf.entity.pedago.Cursus;

@ManagedBean
@SessionScoped
public class EditionCursusBean implements Serializable {

	private static final String thisPage = "editionCursus?faces-redirect=true";
	
	private static final long serialVersionUID = 1L;
	
	private Cursus cursusEdite;
	
	@EJB
	private CursusIBusiness cursusBu;

	@EJB
	private ModuleIBusiness moduleBu;

    @ManagedProperty(value="#{mbConnect}")
    private ConnexionBean mbConnect;
    
	
	public String checkAccess() {

		AccessManager.Profile p = AccessManager.Profile.administration();		
		if (! AccessManager.canAccess(mbConnect.getUtilisateur(), p)) {
			return NavigationBean.forbiddenUrl;
		}
		
		return null;
	}

	public String afficher(Cursus c) {
		
		cursusEdite = c;
		cursusEdite.setModules(moduleBu.getAllForCursus(cursusEdite.getId()));
		
		return thisPage;
	}
	
	public String deplacerMatiereHaut(int matiereId) {
		return thisPage;
	}

	public String deplacerMatiereBas(int matiereId) {		
		return thisPage;
	}

	public String ajouterMatiere(int matiereId) {
		System.out.println("ajout matière...");
		
		// TODO cassé par l'ajout de la table MatiereModule
		/*
		for (Module m : cursusEdite.getModules()) {
			for (MatiereModule matmod : m.getMatiereModules()) {
				if (matmod.getMatiere().getId() == matiereId) {
					final int insertIndex = m.getMatiereModules().indexOf(matmod);
					
					
					m.getMatieres().add(insertIndex,mat);
					
					System.out.println("Matière ajoutée " + insertIndex);
					
					break;
				}
			}
		}
		*/
		
		return thisPage;
	}

	public String retirerMatiere(int matiereId) {

		// TODO cassé par l'ajout de la table MatiereModule
		/*
		for (Module m : cursusEdite.getModules()) {
			for (Matiere mat : m.getMatieres()) {
				if (mat.getId() == matiereId) {
					final int insertIndex = m.getMatieres().indexOf(mat);
					m.getMatieres().remove(mat);
					
					System.out.println("Matière retirée " + insertIndex);
					
					break;
				}
			}
		}
		*/
		
		return thisPage;
	}
	

	//========================================================
	// Getters/Setters
	public Cursus getCursusEdite() {
		return cursusEdite;
	}

	public void setCursusEdite(Cursus cursusEdite) {
		this.cursusEdite = cursusEdite;
	}

	public ConnexionBean getMbConnect() {
		return mbConnect;
	}

	public void setMbConnect(ConnexionBean mbConnect) {
		this.mbConnect = mbConnect;
	}
	
	
}

AppAFCEPFWeb/src/main/java/fr/pocolobo/afcepf/controller/pedago/EditionPromotionBean.java
package fr.pocolobo.afcepf.controller.pedago;

import java.io.Serializable;
import java.util.Calendar;
import java.util.Date;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;

import org.primefaces.event.SelectEvent;
import org.primefaces.model.DefaultScheduleEvent;
import org.primefaces.model.DefaultScheduleModel;
import org.primefaces.model.ScheduleEvent;
import org.primefaces.model.ScheduleModel;

import fr.pocolobo.afcepf.business.api.CoursIBusiness;
import fr.pocolobo.afcepf.business.api.PromotionIBusiness;
import fr.pocolobo.afcepf.controller.AccessManager;
import fr.pocolobo.afcepf.controller.ConnexionBean;
import fr.pocolobo.afcepf.controller.NavigationBean;
import fr.pocolobo.afcepf.entity.pedago.Cours;
import fr.pocolobo.afcepf.entity.pedago.Promotion;
import fr.pocolobo.afcepf.entity.utilisateurs.Stagiaire;

@ManagedBean
@SessionScoped
public class EditionPromotionBean implements Serializable {

	private static final String thisPage = "editionPromotion?faces-redirect=true";
	
	private static final long serialVersionUID = 1L;
	
	private Promotion promoEdite;
	
	private ScheduleModel eventModel;
	
	@EJB
	private PromotionIBusiness promoBu;

	@EJB
	private CoursIBusiness coursBu;

    @ManagedProperty(value="#{mbConnect}")
    private ConnexionBean mbConnect;
    
    private ScheduleEvent event;
    
    private Cours coursSelection;

	//=========================================================================
    
    @PostConstruct
    public void init() {
		eventModel = new DefaultScheduleModel();	
    }
    
    public void onEventSelect(SelectEvent selectEvent) {
    	
        event = (ScheduleEvent) selectEvent.getObject();
        
        try {
        	Cours c = (Cours)event.getDynamicProperties().get("cours");
        	coursSelection = c;
        	
        } catch (Exception e) {
        	e.printStackTrace();
        }
    }
    
    public Date getDateDebut() {
    	return promoBu.getDateDebut(promoEdite.getIdPromotion());
    }
    
    public Date getDateFin() {
    	return promoBu.getDateFin(promoEdite.getIdPromotion());
    }
    
    public void enregistrer() {
    	promoEdite = promoBu.modifier(promoEdite);
    }
    
    public void annuler() {
    	promoEdite = promoBu.rechercherParId(promoEdite.getIdPromotion());
    	
    }
    
	//=========================================================================
    
	public String checkAccess() {

		AccessManager.Profile p = AccessManager.Profile.administration();
		
		if (! AccessManager.canAccess(mbConnect.getUtilisateur(), p)) {
			return NavigationBean.forbiddenUrl;
		}
		
		return null;
	}

	public String afficher(Promotion p) {
		
		promoEdite = p;
		
		loadCours();
		
		return thisPage;
	}
	
	public List<Stagiaire> getStagiaires() {
		return promoBu.getAllStagiaires(promoEdite.getIdPromotion());
	}

	//=========================================================================
	
	public void  loadCours() {

		eventModel.clear();
		
		List<Cours> coursPromo = coursBu.getAllPourPromo(promoEdite.getIdPromotion());
		
		for (Cours c : coursPromo) {
			addCours(c);
		}
		
	}
	
	private void addCours(Cours c) {
		
		String intervenant = c.getIntervenant() == null ? "Non encadré" : c.getIntervenant().getCoordonnees().getNom();
		String msg = c.getMatiere().getNom() + " (" + intervenant + ")";

		for (int i = 0; i < c.getDureeBlocs(); ++i) {
			addDemiJournee(msg, c.getJour(), c.getBlocHoraire() + i == 1, c);
		}
	}
	
	private void addDemiJournee(String msg, Date jour, boolean apresMidi, Cours c) {

        Calendar cal = Calendar.getInstance();
        cal.setTime(jour);
        cal.set(Calendar.HOUR_OF_DAY, apresMidi ? 14 : 0);
        cal.set(Calendar.MINUTE, 0);
		
        Date debut = cal.getTime();
		
        cal.set(Calendar.HOUR_OF_DAY, apresMidi ? 17 : 12);
        cal.set(Calendar.MINUTE, 30);
        
		Date fin = cal.getTime(); 
		
		addEvent(msg, debut, fin, c);
	}
	
	private void addEvent(String nom, Date debut, Date fin, Cours cours) {
		
		DefaultScheduleEvent event = new DefaultScheduleEvent(nom, debut, fin);
		event.setDynamicProperty("cours", cours);
		
		event.setEditable(false);
        eventModel.addEvent(event);
	}

	//=========================================================================
	// Getters/Setters
	
	public ScheduleModel getEventModel() {
		return eventModel;
	}

	public void setEventModel(ScheduleModel eventModel) {
		this.eventModel = eventModel;
	}

	public ConnexionBean getMbConnect() {
		return mbConnect;
	}

	public void setMbConnect(ConnexionBean mbConnect) {
		this.mbConnect = mbConnect;
	}

	public Promotion getPromoEdite() {
		return promoEdite;
	}

	public void setPromoEdite(Promotion promoEdite) {
		this.promoEdite = promoEdite;
	}

	public ScheduleEvent getEvent() {
		return event;
	}

	public void setEvent(ScheduleEvent event) {
		this.event = event;
	}

	public Cours getCoursSelection() {
		return coursSelection;
	}

	public void setCoursSelection(Cours coursSelection) {
		this.coursSelection = coursSelection;
	}
	
}

AppAFCEPFWeb/src/main/java/fr/pocolobo/afcepf/controller/pedago/ListeCursusBean.java
package fr.pocolobo.afcepf.controller.pedago;

import java.util.Date;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;

import fr.pocolobo.afcepf.business.api.CursusIBusiness;
import fr.pocolobo.afcepf.business.api.PromotionIBusiness;
import fr.pocolobo.afcepf.controller.AccessManager;
import fr.pocolobo.afcepf.controller.ConnexionBean;
import fr.pocolobo.afcepf.controller.NavigationBean;
import fr.pocolobo.afcepf.entity.pedago.Cursus;
import fr.pocolobo.afcepf.entity.pedago.Promotion;

@ManagedBean
@ViewScoped
public class ListeCursusBean {
	
	private List<Cursus> listeCursus;

	@EJB
	private CursusIBusiness cursusBu;
	
	@EJB
	private PromotionIBusiness promoBu;

	@ManagedProperty(value = "#{mbConnect}")
	private ConnexionBean mbConnect;

	//=====================================================

	@ManagedProperty(value = "#{editionPromotionBean}")
	private EditionPromotionBean editPromoBean;
	
	private Cursus cursusDeploy;
	
	private String messageErreurDeploy;
	
	private Date dateDeploy;
	
	private int numeroPromoDeploy;
	
	//=====================================================
	
	@PostConstruct
	public void init() {
		listeCursus = cursusBu.getAll();
	}
	
	public String deployer() {
		messageErreurDeploy = "";
		
		if (cursusDeploy == null) {
			messageErreurDeploy = "Veuillez choisir un cursus à déployer.";
			return null;
		}
		
		if (dateDeploy == null) {
			messageErreurDeploy = "Veuillez choisir une date à partir de laquelle déployer le cursus.";
			return null;
		}
		
		if (numeroPromoDeploy < 0) {
			messageErreurDeploy = "Veuillez choisir un numéro de promotion valide.";
			return null;
		}
		
		Promotion p = promoBu.creerPromotion(cursusDeploy, dateDeploy, numeroPromoDeploy);
		
		return editPromoBean.afficher(p);
	}
	
	private void refreshDeploiement() {
		List<Promotion> promos = promoBu.getAllPourCursus(cursusDeploy.getId());
		
		int biggestNumero = 0;
		
		for (Promotion p : promos) {
			if (p.getNumero() > biggestNumero) {
				biggestNumero = p.getNumero();
			}
		}
		
		numeroPromoDeploy = biggestNumero + 1;
		
		dateDeploy = new Date();
	}

	// =====================================================
	// Restriction d'accès

	public String checkAccess() {

		AccessManager.Profile p = AccessManager.Profile.administration();
		if (!AccessManager.canAccess(mbConnect.getUtilisateur(), p)) {
			return NavigationBean.forbiddenUrl;
		}

		return null;
	}

	// =====================================================
	// Recherche

	private String champs;

	public String getChamps() {
		return champs;
	}

	public void setChamps(String champs) {
		this.champs = champs;
	}

	public void rechercher() {
		if (champs == null) {
			setListeCursus(cursusBu.getAll());
			return;
		}

		listeCursus = cursusBu.rechercherParAttributContenu("nom", champs);
	}

	// =====================================================
	// Getters/setters

	public List<Cursus> getListeCursus() {
		return listeCursus;
	}

	public void setListeCursus(List<Cursus> listeCursus) {
		this.listeCursus = listeCursus;
	}

	public ConnexionBean getMbConnect() {
		return mbConnect;
	}

	public void setMbConnect(ConnexionBean mbConnect) {
		this.mbConnect = mbConnect;
	}

	public Cursus getCursusDeploy() {
		return cursusDeploy;
	}

	public void setCursusDeploy(Cursus cursusDeploy) {
		this.cursusDeploy = cursusDeploy;
		
		refreshDeploiement();
	}

	public String getMessageErreurDeploy() {
		return messageErreurDeploy;
	}

	public void setMessageErreurDeploy(String messageErreurDeploy) {
		this.messageErreurDeploy = messageErreurDeploy;
	}

	public Date getDateDeploy() {
		return dateDeploy;
	}

	public void setDateDeploy(Date dateDeploy) {
		this.dateDeploy = dateDeploy;
	}

	public int getNumeroPromoDeploy() {
		return numeroPromoDeploy;
	}

	public void setNumeroPromoDeploy(int numeroPromoDeploy) {
		this.numeroPromoDeploy = numeroPromoDeploy;
	}

	public EditionPromotionBean getEditPromoBean() {
		return editPromoBean;
	}

	public void setEditPromoBean(EditionPromotionBean editPromoBean) {
		this.editPromoBean = editPromoBean;
	}
	
}

AppAFCEPFWeb/src/main/java/fr/pocolobo/afcepf/controller/pedago/ListePromotionsBean.java
package fr.pocolobo.afcepf.controller.pedago;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;

import fr.pocolobo.afcepf.business.api.PromotionIBusiness;
import fr.pocolobo.afcepf.controller.AccessManager;
import fr.pocolobo.afcepf.controller.ConnexionBean;
import fr.pocolobo.afcepf.controller.NavigationBean;
import fr.pocolobo.afcepf.entity.pedago.Promotion;

@ManagedBean
@ViewScoped
public class ListePromotionsBean {
	
	private List<Promotion> listePromos;
	
	@EJB
	private PromotionIBusiness promoBu;

    @ManagedProperty(value="#{mbConnect}")
    private ConnexionBean mbConnect;
    
    private boolean showPassees = false;
    
    private boolean showEnCours = true;
    
    private boolean showFutures = true;

	@PostConstruct
	public void init() {
		//setListePromos(promoBu.getAll());
		rechercher();
	}
	
	public Date getDateDebut(Promotion p) {
		
		if (p == null)
			return null;
		
		return promoBu.getDateDebut(p.getIdPromotion());
	}
	
	public Date getDateFin(Promotion p) {
		
		if (p == null)
			return null;
		
		return promoBu.getDateFin(p.getIdPromotion());
	}

	//=====================================================
	// Restriction d'accès

	public String checkAccess() {

		AccessManager.Profile p = AccessManager.Profile.administration();		
		if (! AccessManager.canAccess(mbConnect.getUtilisateur(), p)) {
			return NavigationBean.forbiddenUrl;
		}
		
		return null;
	}	

	//=====================================================
	// Recherche

	private String champs;
	
	public String getChamps() {
		return champs;
	}

	public void setChamps(String champs) {
		this.champs = champs;
	}
	
	public void rechercher() {
		
		System.out.println("HEEEYY");
		
		if (champs == null) {
			setListePromos(promoBu.getAll());
			filtrer();
			return;
		}
		
		listePromos = promoBu.rechercherParAttributContenu("nom", champs);
		filtrer();
	}
	
	public String getEtat(Promotion p) {
		if (promoBu.isEnCours(p)) 	return "En cours";
		if (promoBu.isPasse(p)) 	return "Passée";
		if (promoBu.isFuture(p)) 	return "Future";
		
		return "";
	}
	
	private void filtrer() {
		
		// On ne filtre pas si tout est décoché
		if (! showEnCours && ! showPassees && ! showFutures)
			return;
		
		List<Promotion> listeFiltre = new ArrayList<Promotion>();
		
		for (Promotion p : listePromos) {
			if (showEnCours && promoBu.isEnCours(p)) {
				listeFiltre.add(p);
			} else if (showPassees && promoBu.isPasse(p)) {
				listeFiltre.add(p);
			} else if (showFutures && promoBu.isFuture(p)) {
				listeFiltre.add(p);
			}
			
			setListePromos(listeFiltre);
		}
	}

	//=====================================================
	// Getters/Setters

	public ConnexionBean getMbConnect() {
		return mbConnect;
	}

	public void setMbConnect(ConnexionBean mbConnect) {
		this.mbConnect = mbConnect;
	}

	public List<Promotion> getListePromos() {
		return listePromos;
	}

	public void setListePromos(List<Promotion> listePromos) {
		this.listePromos = listePromos;
	}

	public boolean isShowPassees() {
		return showPassees;
	}

	public void setShowPassees(boolean showPassees) {
		this.showPassees = showPassees;
	}

	public boolean isShowEnCours() {
		return showEnCours;
	}

	public void setShowEnCours(boolean showEnCours) {
		this.showEnCours = showEnCours;
	}

	public boolean isShowFutures() {
		return showFutures;
	}

	public void setShowFutures(boolean showFutures) {
		this.showFutures = showFutures;
	}

	
}

AppAFCEPFWeb/src/main/webapp/pedago/editionCursus.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:b="http://bootsfaces.net/ui">

<h:body>

	<ui:composition template="/template.xhtml">

		<ui:define name="head">
			<title>#{navigationBean.websiteTitle} | Edition cursus</title>

			<link rel="stylesheet" type="text/css" href="css/editionCursus.css" />
			
			<!-- Accès restreint -->
			<f:metadata>
			    <f:viewAction action="#{editionCursusBean.checkAccess()}" />
			</f:metadata>
		</ui:define>

		<ui:define name="content">
			<div id="enTete">
				<img src="images/cursus/logo-afc-coul-transp.png" alt="image" />
				<h2>Edition du cursus #{editionCursusBean.cursusEdite.nom}</h2>
<!-- 				<h3>Des formations au service de l'emploi dans le numérique</h3> -->
			</div>

			<div id="cursusMainFlex" class="conteneur">
				<div id="cursusDescription" class="champsgroupes">
					<h3>Description</h3>
					<b:panelGrid columns="2">
						<h:outputLabel value="Nom :" />
						<b:inputText value="#{editionCursusBean.cursusEdite.nom}" />
						
						<h:outputLabel value="Code :" />
						<b:inputText value="#{editionCursusBean.cursusEdite.code}" />
						
						<h:outputLabel value="Description :" />
						<b:inputTextarea value="#{editionCursusBean.cursusEdite.description}" />
					</b:panelGrid>
				</div>

				<div id="cursusContenu" class="champsgroupes">
					<h3>Contenu pédagogique</h3>

					<h:form id="modulesForm">
						<table class="tableCursus">
							<ui:repeat var="module"
								value="#{editionCursusBean.cursusEdite.modules}">

								<tr>
									<th colspan="4" class="moduleRow">#{module.nom}</th>
								</tr>

								<ui:repeat var="mm" value="#{module.matiereModules}">
									<tr>
										<th></th>
										<td class="matiereRow">
											<div class="composantRecherche">
												<b:inputText value="#{mm.matiere.nom}"
													placeholder="Entrer une matière" typeahead="true"
													typeahead-values="#{matiereRechercheBean.getAllCSV()}"
													tiny-screen="full-width" />
											</div>
										</td>
										<td class="matiereRow">
											#{mm.matiere.dureeDemiJournees / 2} jour(s)
										</td>
										<td class="matiereRow">
											<b:commandButton
												action="#{editionCursusBean.ajouterMatiere(matiere.id)}"  styleClass="roundButton"
												 style= "background-color: rgba(111, 207, 151, 0.42);"
												value="" icon-awesome="plus" update="@form" />
											
											<b:commandButton
												action="#{editionCursusBean.retirerMatiere(matiere.id)}" styleClass="roundButton"
												 style= "background-color: rgba(111, 207, 151, 0.42);"
												value="" icon-awesome="minus" update="@form" />
												
<!-- 											<b:commandButton -->
<!-- 												action="#{editionCursusBean.deplacerMatiereHaut(matiere.id)}" -->
<!-- 												value="" icon-awesome="arrow-up" update="@form" /> -->
											
<!-- 											<b:commandButton -->
<!-- 												action="#{editionCursusBean.deplacerMatiereBas(matiere.id)}" -->
<!-- 												value="" icon-awesome="arrow-down" update="@form" /> -->
										</td>
									</tr>
								</ui:repeat>
							</ui:repeat>
						</table>
					</h:form>
				</div>
			</div>

		</ui:define>

	</ui:composition>

</h:body>
</html>

AppAFCEPFWeb/src/main/webapp/pedago/editionPromotion.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:b="http://bootsfaces.net/ui" xmlns:p="http://primefaces.org/ui">

<h:body>
	<ui:composition template="/template.xhtml">
		<ui:define name="head">
			<title>#{navigationBean.websiteTitle} | Edition promotion</title>

			<link rel="stylesheet" type="text/css" href="css/editionPromo.css" />

			<!-- Accès restreint -->
			<f:metadata>
				<f:viewAction action="#{editionPromotionBean.checkAccess()}" />
			</f:metadata>
		</ui:define>

		<ui:define name="content">
			<div id="enTete">
				<img src="images/cursus/logo-afc-coul-transp.png" alt="image" />
				<h2>Edition de la promotion
				#{editionPromotionBean.promoEdite.cursus.code}#{editionPromotionBean.promoEdite.numero}</h2>
			</div>
			
			<b:form id="editionPromo">
				<div class="champsgroupes">
					<div id="promoDescription">
						<h4>Description</h4>
						<b:panelGrid id="grid" cellpadding="6" columns="2"
							style="margin-bottom:10px">
							<p:outputLabel value="Numéro" />
							<b:inputText value="#{editionPromotionBean.promoEdite.numero}" />
							
							<p:outputLabel value="Capacité minimale" />
							<b:inputText value="#{editionPromotionBean.promoEdite.capaciteMin}" />
							
							<p:outputLabel value="Capacité maximale" />
							<b:inputText value="#{editionPromotionBean.promoEdite.capaciteMax}" />
							
							<p:outputLabel value="Date de début" />
							<b:dateTimePicker show-time="false" readonly="true"
									value="#{editionPromotionBean.getDateDebut()}" />
									
							<p:outputLabel value="Date de fin" />
							<b:dateTimePicker show-time="false" readonly="true"
									value="#{editionPromotionBean.getDateFin()}" />
									
							<p:outputLabel value="Stagiaires affectés (#{editionPromotionBean.getStagiaires().size()})" />
							<select name="selectStagiaire" size="4">
								<ui:repeat var="stagiaire"
									value="#{editionPromotionBean.getStagiaires()}">
									<option value="#{stagiaire.id}">#{stagiaire.coordonnees.nom}
										#{stagiaire.coordonnees.prenom}</option>
								</ui:repeat>
							</select>
						</b:panelGrid>
					</div>
				</div>
				
				<div class="promoHFlex">
					<div id="promoCalendrier">
						<h4>Calendrier de formation</h4>
						<p:schedule initialDate="#{editionPromotionBean.dateDebut}"
							allDaySlot="false" aspectRatio="2.3" firstHour="9"
							minTime="9:00:00" maxTime="18:00:00"
							id="schedule" value="#{editionPromotionBean.eventModel}"
							widgetVar="agendaPromo" timeZone="GMT+2" locale="fr">
							<p:ajax event="eventSelect"
								listener="#{editionPromotionBean.onEventSelect}"
								update="eventDetails" />

						</p:schedule>
					</div>
					<div id="promoInspecteur">
						<h4>Détail du cours</h4>

						<b:panelGrid id="eventDetails" columns="2">

							<h:panelGroup styleClass="eventDetailDiv"
								rendered="#{editionPromotionBean.coursSelection != null}"
								layout="block">

								<p:outputLabel value="Matière"></p:outputLabel>
								<b:inputText class="" readonly="true"
									value="#{editionPromotionBean.coursSelection.matiere.nom}" />
								<p:outputLabel value="Date"></p:outputLabel>
								<b:datepicker
									value="#{editionPromotionBean.coursSelection.jour}"></b:datepicker>
								<p:outputLabel value="Début"></p:outputLabel>
								<b:selectOneMenu
									value="#{editionPromotionBean.coursSelection.blocHoraire}">
									<f:selectItem itemLabel="Matin" itemValue="0" />
									<f:selectItem itemLabel="Après-midi" itemValue="1" />
								</b:selectOneMenu>
								<p:outputLabel value="Durée"></p:outputLabel>
								<b:selectOneMenu
									value="#{editionPromotionBean.coursSelection.dureeBlocs}">
									<f:selectItem itemLabel="Demi-journée" itemValue="0" />
									<f:selectItem itemLabel="Journée entière" itemValue="1" />
								</b:selectOneMenu>
								<p:outputLabel value="Intervenant"></p:outputLabel>
								<b:inputText class="" readonly="true"
									value="#{editionPromotionBean.coursSelection.intervenant.coordonnees.nom}" />
							</h:panelGroup>
						</b:panelGrid>


					</div>
				</div>

				<div class="centerButtons">
					<b:commandButton action="#{editionPromotionBean.enregistrer()}"
						value="Enregistrer" styleClass="boutonSpecial"  update="@form" />
					<b:commandButton action="#{editionPromotionBean.annuler()}"
						value="Annuler" styleClass="boutonGris" update="@form" />
				</div>
			</b:form>
		</ui:define>
	</ui:composition>

</h:body>
</html>