AppAFCEPFWeb/src/main/java/fr/pocolobo/afcepf/controller/AccueilBean.java
package fr.pocolobo.afcepf.controller;

import java.io.Serializable;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;

@ManagedBean
@SessionScoped
public class AccueilBean implements Serializable {

	private static final long serialVersionUID = 1L;

    @ManagedProperty(value="#{mbConnect}")
    private ConnexionBean mbConnect;

	public String getMessageBienvenue() {
		
		return mbConnect.getUtilisateur() == null ? 
				"Bienvenue sur le portail numérique de l'EQL"
				: "Bonjour " + mbConnect.getNomAffiche();
	}

	public ConnexionBean getMbConnect() {
		return mbConnect;
	}

	public void setMbConnect(ConnexionBean mbConnect) {
		this.mbConnect = mbConnect;
	}
	
	

}

AppAFCEPFWeb/src/main/java/fr/pocolobo/afcepf/controller/AgendaBean.java
package fr.pocolobo.afcepf.controller;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;

import org.primefaces.model.DefaultScheduleEvent;
import org.primefaces.model.DefaultScheduleModel;
import org.primefaces.model.ScheduleModel;

import fr.pocolobo.afcepf.business.api.CoursIBusiness;
import fr.pocolobo.afcepf.business.api.StagiaireIBusiness;
import fr.pocolobo.afcepf.entity.pedago.Cours;
import fr.pocolobo.afcepf.entity.pedago.Promotion;

@ManagedBean
@ViewScoped
public class AgendaBean implements Serializable {

	private static final long serialVersionUID = 1L;

	private ScheduleModel eventModel;

    @ManagedProperty(value="#{mbConnect}")
    private ConnexionBean mbConnect;
    
    @EJB
    private StagiaireIBusiness stagiaireBu;
    
    @EJB
    private CoursIBusiness coursBu;
    
	@PostConstruct
	public void init() {
		eventModel = new DefaultScheduleModel();
		
		if (mbConnect.isStagiaire()) {
			System.out.println("Load stagiaire");
			loadStagiaire();
		}
	}
	
	//=========================================================================
	// Accès restreint (utilisateur identifié)
	
	public String checkAccess() {
	
		if (! mbConnect.isConnecte()) {
			return NavigationBean.forbiddenUrl;
		}
		
		return null;
	}

	//=========================================================================
	// Getters/Setters
	
	public ScheduleModel getEventModel() {
		return eventModel;
	}

	public void setEventModel(ScheduleModel eventModel) {
		this.eventModel = eventModel;
	}

	public ConnexionBean getMbConnect() {
		return mbConnect;
	}

	public void setMbConnect(ConnexionBean mbConnect) {
		this.mbConnect = mbConnect;
	}
	
	//=========================================================================
	
	private void loadStagiaire() {
		List<Promotion> promos = stagiaireBu.getPromotions(mbConnect.getUtilisateur().getId());
		List<Cours> cours = new ArrayList<Cours>();
		
		for (Promotion p : promos) {
			List<Cours> coursPromo = coursBu.getAllPourPromo(p.getIdPromotion());
			
			for (Cours c : coursPromo) {
				cours.add(c);
			}
		}
		
		for (Cours c : cours) {
			addCours(c);
		}
	}
	
	private void addCours(Cours c) {
		
		String intervenant = c.getIntervenant() == null ? "Non encadré" : c.getIntervenant().getCoordonnees().getNom();
		String msg = c.getMatiere().getNom() + " (" + intervenant + ")";

		for (int i = 0; i < c.getDureeBlocs(); ++i) {
			addDemiJournee(msg, c.getJour(), c.getBlocHoraire() + i == 1);
		}
	}
	
	private void addDemiJournee(String msg, Date jour, boolean apresMidi) {

        Calendar cal = Calendar.getInstance();
        cal.setTime(jour);
        cal.set(Calendar.HOUR_OF_DAY, apresMidi ? 14 : 0);
        cal.set(Calendar.MINUTE, 0);
		
        Date debut = cal.getTime();
		
        cal.set(Calendar.HOUR_OF_DAY, apresMidi ? 17 : 12);
        cal.set(Calendar.MINUTE, 30);
        
		Date fin = cal.getTime(); 
		
		addEvent(msg, debut, fin);
	}
	
	private void addEvent(String nom, Date debut, Date fin) {
		
		DefaultScheduleEvent event = new DefaultScheduleEvent(nom, debut, fin);
		event.setEditable(false);
        eventModel.addEvent(event);
	}
}



AppAFCEPFWeb/src/main/java/fr/pocolobo/afcepf/controller/AlertesAdministrationBean.java
package fr.pocolobo.afcepf.controller;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;

import fr.pocolobo.afcepf.business.api.notification.NotificationIBusiness;
import fr.pocolobo.afcepf.entity.notification.Notification;

@ManagedBean
@ViewScoped
public class AlertesAdministrationBean {

	@EJB
	NotificationIBusiness notifBu;
	
	@ManagedProperty(value="#{alertManagerBean}")
	AlertManagerBean alertManager;
	
	List<Notification> all;
	
	@PostConstruct
	void init() {
		
		alertManager.refresh();
		
		all = notifBu.getAll();
	}
	
	public List<Notification> getActionsDossiers() {
		List<Notification> r = new ArrayList<Notification>();
		
		for (Notification n : all) {
			if (n.getType() == Notification.Type.dossierCandidature)
				r.add(n);
		}
		
		return r;
	}

	public List<Notification> getActionsPromos() {
		List<Notification> r = new ArrayList<Notification>();
		
		for (Notification n : all) {
			if (n.getType() == Notification.Type.promotion)
				r.add(n);
		}
		
		return r;
	}

	public AlertManagerBean getAlertManager() {
		return alertManager;
	}

	public void setAlertManager(AlertManagerBean alertManager) {
		this.alertManager = alertManager;
	}
	
	
}

AppAFCEPFWeb/src/main/java/fr/pocolobo/afcepf/controller/ConnexionBean.java
package fr.pocolobo.afcepf.controller;

import java.util.ArrayList;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;

import fr.pocolobo.afcepf.business.api.UtilisateurIBusiness;
import fr.pocolobo.afcepf.entity.utilisateurs.Utilisateur;
import fr.pocolobo.afcepf.entity.utilisateurs.UtilisateurHelper;

@ManagedBean(name = "mbConnect")
@SessionScoped
public class ConnexionBean {

	public UtilisateurIBusiness getIbuUtilisateur() {
		return ibuUtilisateur;
	}

	public void setIbuUtilisateur(UtilisateurIBusiness ibuUtilisateur) {
		this.ibuUtilisateur = ibuUtilisateur;
	}

	private String login;
	private String password;
	private Utilisateur utilisateur;
	private String message;

	private ArrayList<ConnexionListener> listeners;

	@EJB
	private UtilisateurIBusiness ibuUtilisateur;


	public ConnexionBean() {
		super();

		listeners = new ArrayList<ConnexionListener>();
	}

	public String getNomAffiche() {

		String nomAffiche;

		if (utilisateur == null) {
			nomAffiche = "Non connecté";
		} else {
			nomAffiche = utilisateur.getCoordonnees().getPrenom() + " " + utilisateur.getCoordonnees().getNom();
		}

		return nomAffiche;

	}

	public String getphotoAffichee() {

		String photoAffichee;

		if (utilisateur == null) {
			photoAffichee = "";
		} else {
			photoAffichee = utilisateur.getCoordonnees().getPhoto();
		}
		return photoAffichee;

	}

	public String connect() {

		utilisateur = ibuUtilisateur.connecter(login, password);
		String retour = "";

		if (utilisateur != null) {
			retour = "/index.xhtml?faces-redirect=true";
			message = "";
		} else {
			retour = "/connexion.xhtml?faces-redirect=true";
			message = "Login ou mot de passe incorrect. Veuillez recommencer.";
		}

		changementUtilisateur();

		return retour;
	}

	public String deconnect() {
		HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(true);
		session.invalidate();

		changementUtilisateur();

		return "/connexion.xhtml?faces-redirect=true";
	}

	public String getLogin() {
		return login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Utilisateur getUtilisateur() {
		return utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public boolean isConnecte() {
		return utilisateur != null;
	}

	public boolean isStagiaire() {
		if (utilisateur == null)
			return false;

		return UtilisateurHelper.isStagiaire(utilisateur);
	}

	public boolean isIntervenant() {
		if (utilisateur == null)
			return false;

		return UtilisateurHelper.isIntervenant(utilisateur);
	}

	public boolean isAdministration() {
		if (utilisateur == null)
			return false;

		return UtilisateurHelper.isAdministration(utilisateur);
	}


	//===========================================================
	// Listeners

	public void addListener(ConnexionListener l) {

		if (! listeners.contains(l))
			listeners.add(l);
	}

	public void changementUtilisateur() {
		for (ConnexionListener l : listeners) {
			l.utilisateurChanged();
		}
	}
}

AppAFCEPFWeb/src/main/java/fr/pocolobo/afcepf/controller/EditionCandidatureBean.java
package fr.pocolobo.afcepf.controller;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;

import fr.pocolobo.afcepf.business.api.CiviliteIBusiness;
import fr.pocolobo.afcepf.business.api.CoordonneesIBusiness;
import fr.pocolobo.afcepf.business.api.DossierCandidatureIBusiness;
import fr.pocolobo.afcepf.business.api.PromotionIBusiness;
import fr.pocolobo.afcepf.business.api.PromotionStagiaireIBusiness;
import fr.pocolobo.afcepf.business.api.StagiaireIBusiness;
import fr.pocolobo.afcepf.entity.Civilite;
import fr.pocolobo.afcepf.entity.DossierCandidature;
import fr.pocolobo.afcepf.entity.pedago.Promotion;
import fr.pocolobo.afcepf.entity.pedago.PromotionStagiaire;

@ManagedBean(name = "editionCandidatureBean")
@SessionScoped
public class EditionCandidatureBean {

	private static final String thisPage = "/editionCandidature?faces-redirect=true";
	
	private DossierCandidature dossCand;
	
	private List<Civilite> civilites;
	
	private Promotion promoAffect;

	@EJB
	private CoordonneesIBusiness coordonnesBu;
	@EJB
	private DossierCandidatureIBusiness ibuCand;
	@EJB
	private CiviliteIBusiness ibuCivil;
	@EJB
	private PromotionIBusiness promoBu;
	@EJB
	private StagiaireIBusiness stagiaireBu;
	@EJB
	private PromotionStagiaireIBusiness promoStagiaireBu;
	
	@ManagedProperty(value = "#{alertManagerBean}")
	private AlertManagerBean alertManager;

	@ManagedProperty(value = "#{mbConnect}")
	private ConnexionBean mbConnect;

	@PostConstruct
	public void init() {
		civilites = ibuCivil.getAll();
		//System.out.println("Nb civilite : " + civilites.size());
		
	}
	
	public void enregistrer() { 

		coordonnesBu.modifier(dossCand.getStagiaire().getCoordonnees());
		stagiaireBu.modifier(dossCand.getStagiaire());
		ibuCand.modifier(dossCand);
		
		System.out.println("dossier modifié");
	}

	public String getTitrePage() {
		return ! mbConnect.isConnecte() ? "" : 
			(mbConnect.isStagiaire() ? "Compléter ma candidature" : "Gestion dossier de candidature");
	}
	
	public String affiche(DossierCandidature dc) {
		
		dossCand = dc;
		
		return thisPage;
	}
	
	public String getAvancement() {
		if (dossCand == null) {
			return "";
		}
		
		if (dossCand.isRefuse()) {
			return "Refusé";
		}
		
		if (dossCand.isAccepte()) {
			return "Accepté";
		}
		
		switch (dossCand.getAvancement()) {
		case attenteRI:
			return "En attente de réunion d'information";
		case attenteAffectation:
			return "En attente d'affectation";
		case initial:
			return "En cours";
		case attenteEI:
			return "En attente d'un entretin individuel";
		default:
			return "";
		}
	}
	
	public boolean isDossierClos() {
		return dossCand != null && (dossCand.isRefuse() || dossCand.isAccepte());
	}
	
	public String accepterDossier() {
		
		// Acceptation du dossier
		dossCand.setAccepte(true);
		ibuCand.modifier(dossCand);
		
		// Ajout affectation à la promotion
		PromotionStagiaire ps = new PromotionStagiaire();
		ps.setPromotion(promoAffect);
		ps.setStagiaire(dossCand.getStagiaire());
		promoStagiaireBu.ajouter(ps);
		
        alertManager.refresh();
		
		return thisPage;
	}
	
	public String refuserDossier() {
		dossCand.setRefuse(true);
		ibuCand.modifier(dossCand);

        alertManager.refresh();
        
		return thisPage;
	}
	
	public List<Promotion> getPromos() {
		if (dossCand == null)
			return new ArrayList<Promotion>();
		
		return promoBu.getAllPourCursus(dossCand.getCursusDemande().getId());
	}
	
	// =====================================================
	// Restriction d'accès

	public String checkAccess() {

		if (! mbConnect.isConnecte()) {
			return NavigationBean.forbiddenUrl;
		}

		return null;
	}
	// =====================================================

	public DossierCandidature getDossCand() {
		return dossCand;
	}


	public void setDossCand(DossierCandidature dossCand) {
		this.dossCand = dossCand;
	}

	public DossierCandidatureIBusiness getIbuCand() {
		return ibuCand;
	}

	public void setIbuCand(DossierCandidatureIBusiness ibuCand) {
		this.ibuCand = ibuCand;
	}

	public ConnexionBean getMbConnect() {
		return mbConnect;
	}

	public void setMbConnect(ConnexionBean mbConnect) {
		this.mbConnect = mbConnect;
	}


	public List<Civilite> getCivilite() {
		return civilites;
	}


	public void setCivilite(List<Civilite> civilite) {
		this.civilites = civilite;
	}

	public CiviliteIBusiness getIbuCivil() {
		return ibuCivil;
	}

	public void setIbuCivil(CiviliteIBusiness ibuCivil) {
		this.ibuCivil = ibuCivil;
	}

	public List<Civilite> getCivilites() {
		return civilites;
	}

	public void setCivilites(List<Civilite> civilites) {
		this.civilites = civilites;
	}

	public Promotion getPromoAffect() {
		return promoAffect;
	}

	public void setPromoAffect(Promotion promoAffect) {
		this.promoAffect = promoAffect;
	}

	public AlertManagerBean getAlertManager() {
		return alertManager;
	}

	public void setAlertManager(AlertManagerBean alertManager) {
		this.alertManager = alertManager;
	}
	
	

}

AppAFCEPFWeb/src/main/java/fr/pocolobo/afcepf/controller/GenericRechercheBean.java
package fr.pocolobo.afcepf.controller;

import java.util.List;

import fr.pocolobo.afcepf.business.api.GenericIBusiness;

public abstract class GenericRechercheBean<T> {

	private String champs;
	private List<T> resultats;
	
	protected abstract String getRechercheAttribut();
	
	protected abstract GenericIBusiness<T> getBusiness();
	
	public String getChamps() {
		return champs;
	}

	public void setChamps(String champs) {
		this.champs = champs;
	}

	public List<T> getResultats() {
		return resultats;
	}

	public void setResultats(List<T> resultats) {
		this.resultats = resultats;
	}

	public String rechercher() {
		resultats = getBusiness().rechercherParAttributContenu(getRechercheAttribut(), champs);
		return "testRecherche.xhtml?use-redirect=true";
	}
}

AppAFCEPFWeb/src/main/java/fr/pocolobo/afcepf/controller/MatiereRechercheBean.java
package fr.pocolobo.afcepf.controller;

import java.util.List;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import fr.pocolobo.afcepf.business.api.GenericIBusiness;
import fr.pocolobo.afcepf.business.api.MatiereIBusiness;
import fr.pocolobo.afcepf.entity.pedago.Matiere;

@ManagedBean
@SessionScoped
public class MatiereRechercheBean extends GenericRechercheBean<Matiere> {
	
	@EJB
	private MatiereIBusiness bu;
	
	private List<Matiere> allMatieres;
	
	private Matiere selection;

	@PostConstruct
	public void init() {
		allMatieres = bu.getAll();
	}
	
	@Override
	protected String getRechercheAttribut() {
		return "nom";
	}
	
	@Override
	protected GenericIBusiness<Matiere> getBusiness() {
		return bu;
	}
	
	public GenericIBusiness<Matiere> getBu() {
		return bu;
	}

	public void setBu(MatiereIBusiness bu) {
		this.bu = bu;
	}


	public List<Matiere> getAllMatieres() {
		return allMatieres;
	}

	public String getAllCSV() {
		String result = "";
		
		for (int i = 0; i < allMatieres.size(); ++i) {

			if (i > 0)
				result += ", ";
			
			result += "\"" + allMatieres.get(i).getNom() + "\"";
		}
		
		return result;
	}

	public void setAllMatieres(List<Matiere> allMatieres) {
		this.allMatieres = allMatieres;
	}

	public Matiere getSelection() {
		return selection;
	}

	public void setSelection(Matiere selection) {
		this.selection = selection;
	}
}

AppAFCEPFWeb/src/main/webapp/connexion.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:b="http://bootsfaces.net/ui">

<h:body>

	<ui:composition template="/template.xhtml">

		<ui:define name="head">
			<title>#{navigationBean.websiteTitle}</title>
		</ui:define>

		<ui:define name="content">
			<link rel="stylesheet" type="text/css" href="css/connexion.css" />
			<link rel="stylesheet" type="text/css" href="css/index.css" />

			<div id="enTete">
				<img src="images/cursus/logo-afc-coul-transp.png" alt="image" />
				<h1>Page de connexion</h1>
			</div>

			<h:form>
				<div class="conteneur">
					<div class="card">
						<h2>Identifiez-vous</h2>
						<h:panelGroup rendered="#{mbConnect.isConnecte()}">
							<p>Vous êtes connecté en tant que
								#{mbConnect.getNomAffiche()}.</p>
							<div class="bouton">
								<h:commandButton action="#{mbConnect.deconnect()}"
									value="Me déconnecter"
									 styleClass="boutonSpecial"/>
							</div>
						</h:panelGroup>

						<!-- 			Pas d'utilisateur connecté -->
						<h:panelGroup rendered="#{!mbConnect.isConnecte()}">
							<div>
								<table>
									<tr>
										<th>Login :</th>
										<td><b:inputText value="#{mbConnect.login}" /></td>
									</tr>
									<tr>
										<th>Mot de Passe :</th>
										<td><b:inputSecret value="#{mbConnect.password}" /></td>
									</tr>
								</table>
							</div>
							<div class="bouton">
								<h:commandButton action="#{mbConnect.connect()}" value="Connexion" styleClass="boutonSpecial" />
	
								<div class="messageErreur">
									<h:outputLabel class="messageErreur"
										value="#{mbConnect.message}" />
								</div>
							</div>
						</h:panelGroup>
					</div>
				</div>
			</h:form>

		</ui:define>

	</ui:composition>

</h:body>
</html>


AppAFCEPFWeb/src/main/webapp/index.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:b="http://bootsfaces.net/ui" xmlns:p="http://primefaces.org/ui">

<h:body>
	<ui:composition template="/template.xhtml">

		<ui:define name="head">
			<title>#{navigationBean.websiteTitle}</title>
			
			<f:metadata>
				<f:viewAction action="#{notificationBean.pollNotifications()}" />
			</f:metadata>
		</ui:define>

		<ui:define name="content">
			<!-- 			Pas d'utilisateur connecté -->
			<h:panelGroup layout="block" rendered="#{!mbConnect.isConnecte()}">
				<link rel="stylesheet" type="text/css" href="css/index.css" />

				<div id="enTete">
					<img src="images/cursus/logo-afc-coul-transp.png" alt="image" />
					<h1>Bienvenue à l'AFCEPF - L'Ecole de Qualité Logicielle</h1>
				</div>

				<div class="conteneur">
					<div class="colBis">
						<div id="texteBisG" class="card">
							<h4>Je suis déjà enregistré</h4>
							
							<div class="hflex">
								<b:iconAwesome value="heartbeat" spin="false" size="2x" />
								<b:link href="connexion" value="Accéder à mon espace perso" />
							</div>
								
							<div class="hflex">
								<b:iconAwesome value="coffee" spin="false" size="2x" />
								<b:link href="#" value="J'ai oublié mes identifiants" />
							</div>
						</div>
					</div>

					<div class="colBis">
						<div id="texteBisD" class="card">
							<h4>Je souhaite candidater pour une formation</h4>
							
							<div class="hflex">
								<b:iconAwesome value="group" spin="false" size="2x" />
								<b:link href="precandidature" value="Déposer une candidature" />
							</div>
						</div>
					</div>

				</div>
			</h:panelGroup>

			<!-- 			Stagiaire -->
			<h:panelGroup layout="block" rendered="#{mbConnect.isStagiaire()}">
				<link rel="stylesheet" type="text/css" href="css/index.css" />

				<div id="enTete">
					<img src="images/cursus/logo-afc-coul-transp.png" alt="image" />
					<h1>Mon Agenda</h1>
				</div>

				<div class="conteneur">
					<div class="colBis card">
						<p:schedule allDaySlot="false" aspectRatio="2.3" firstHour="9"
							minTime="9:00:00" maxTime="18:00:00" styleClass="agendaPetit"
							view="agendaWeek" id="schedule" value="#{agendaBean.eventModel}"
							widgetVar="agendaPerso" timeZone="GMT+2" locale="fr">
						</p:schedule>
					</div>

					<div class="colBis card">
						<div id="retards">
							<h4><i class="pi pi-bell"></i>  Mes Retards </h4>
							<br />
							<h5>0</h5>
							
						</div>
						<div id="absences">
							<h4> <i class="pi pi-home"></i>  Mes Absences</h4>
							<br /> 
							<h5>0</h5><br/>
						</div>
					</div>
				</div>
				<!-- FIN DU DIV CONTENEUR -->
			</h:panelGroup>
			
			<!-- 			Intervenant -->
			<h:panelGroup layout="block" rendered="#{mbConnect.isIntervenant()}">
				<h3>Bonjour intervenant</h3>
			</h:panelGroup>

			<!-- 			Admin -->
			<h:panelGroup layout="block"
				rendered="#{mbConnect.isAdministration()}">

				<link rel="stylesheet" type="text/css" href="css/index.css" />

				<div id="enTete">
					<div>
						<img src="images/cursus/logo-afc-coul-transp.png" alt="image" />
					</div>
					<div>
						<h1>Bienvenue dans votre espace</h1>
					</div>
				</div>

				<!-- 					ICI DEMARRE LE BODY -->

				<!-- FIN DU DIV DU HAUT -->

				<div class="conteneur">
					<div class="colBis card">
						<p:schedule allDaySlot="false" aspectRatio="2.3" firstHour="9"
							minTime="9:00:00" maxTime="18:00:00" styleClass="agendaPetit"
							view="agendaWeek" id="schedule2" value="#{agendaBean.eventModel}"
							widgetVar="agendaPerso" timeZone="GMT+2" locale="fr">
						</p:schedule>

					</div>
					<!-- FIN DE LA COLONNE GAUCHE -->
					<div class="colBis card">
						<div class="hflex">
							<b:iconAwesome name="spinner" spin="true" size="2x" />
							<p:outputLabel value="Promotions à compléter"
								labelStyle="width:80px;" style="font-size:small" />
						</div>
						<ui:repeat var="action" value="#{alertesAdministrationBean.actionsPromos}">
							<div><b:link href="#{action.url}">#{action.shortMessage}</b:link></div>
						</ui:repeat>

<!-- 						<div class="hflex"> -->
<!-- 							<b:iconAwesome name="refresh" spin="true" size="2x" /> -->
<!-- 							<p:outputLabel value="Urgences du jour" labelStyle="width:80px;" -->
<!-- 								style="font-size:small;" /> -->
<!-- 						</div> -->

						<div class="hflex">
							<b:iconAwesome name="cog" spin="true" size="2x" />
							<p:outputLabel value="Candidatures en attente"
								labelStyle="width:80px;" style="font-size:small" />
						</div>
						<ui:repeat var="action" value="#{alertesAdministrationBean.actionsDossiers}">
							<div><b:link href="#{action.url}">#{action.shortMessage}</b:link></div>
						</ui:repeat>
						
						
						<div class="hflex">
							<b:iconAwesome name="circle-o-notch" spin="true" size="2x" />
							<p:outputLabel value="Traiter les indisponibilités"
								labelStyle="width:80px;" style="font-size:small" />
						</div>
						
					</div>
					<!-- FIN DU DIV COLONNE DROITE -->
				</div>
				<!-- ICI LA FIN DU DIV CONTENEUR -->
			</h:panelGroup>

		</ui:define>

	</ui:composition>

</h:body>
</html>